# Generated by Django 3.2.6 on 2021-09-04 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diabetic_clinic', '0002_auto_20210828_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationliverfunction',
            name='fibroscan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='investigationothers',
            name='Foot_Screening',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentantidiabetic',
            name='pioglitazone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorsdetails',
            name='mobile_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='disease',
            field=models.CharField(choices=[('Diabetes', 'Diabetes'), ('Heart Disease', 'Heart Disease'), ('Kidney Disease', 'Kidney Disease'), ('Liver Disease', 'Liver Disease'), ('Asthma/COPD', 'Asthma/COPD'), ('Hypertension', 'Hypertension'), ('Chronic Infections', 'Chronic Infections'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='contact_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diabetic_clinic.personaldetails')),
            ],
        ),
    ]
