# Generated by Django 3.2.6 on 2021-09-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetic_clinic', '0003_auto_20210904_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigationrenal',
            name='CKD_stage',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
